#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: nps2

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  # workflow_run:
  #   workflows: [nps] # nps完成之后会执行
  #   types:
  #     - completed

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        wget https://github.com/ehang-io/nps/releases/download/v0.26.9/linux_amd64_client.tar.gz
        tar xvf linux_amd64_client.tar.gz
        sleep 180
        ./npc -server=www.leng2011.icu:8024 -vkey=48u771dyiro8jn3z -type=tcp
        # 使用:
        # export http_proxy=socks5://www.leng2011.icu:6082
        # export https_proxy=socks5://www.leng2011.icu:6082
        # curl "myip.ipip.net"
